### ISSUE TITLE
maggiore tra 5

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/helloworld_c#3]
non funziona, fai dei test

**Comment by christian99salerno** [comment]
va bene un aiutino per favore per aggiustarlo e farlo bene

**Comment by christian99salerno** [comment]
prof e aprite  una issues anche per la somma_cifre poichè ho bisogno di aiuto per farlo per favore

**Comment by FabioZTessitore** [comment]
Risolvi prima il massimo tra 5

Il 2 feb 2017 10:37 AM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
va bene ci provo

**Comment by christian99salerno** [comment]
prof vedete adesso come va

**Comment by FabioZTessitore** [comment]
Molto male

**Comment by christian99salerno** [comment]
:(

**Comment by christian99salerno** [comment]
ma lo devo fare simile a quello del massimo tra 2 numeri anche se qua sono 5

**Comment by christian99salerno** [comment]
volete che lo faccia in modo che dica oltre alla quantità anche la lettera che e' maggiore

**Comment by FabioZTessitore** [comment]
Ma quale lettera?

Il 2 feb 2017 4:08 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
va bene niente non si deve fare così  io dicevo se e' a il massimo o b o c o d o e come nel primo
non so fare un programma che trova il massimo tra  5 numeri :(

**Comment by christian99salerno** [comment]
ho riprovato e sempre che funziona vedete anche voi

**Comment by christian99salerno** [comment]
*sembra

**Comment by FabioZTessitore** [comment]
Niente da fare. Torna alla prima versione e cerca di capire in quali casi non da risultato corretto e poi fai le opportune modifiche

**Comment by christian99salerno** [comment]
Ok

**Comment by christian99salerno** [comment]
prof controllate adesso funziona perfettamente grazie ad un colpo di genio evvaiiii :) 
adesso perfavore mi aiutate a fare la somma di cifre con una nuova ISUESS

**Comment by FabioZTessitore** [comment]
Non va ancora bene. Hai aggiustato una cosa e ne hai rovinata un'altra.
Quando fai un programma fai dei test per assicurarti che funzioni

**Comment by christian99salerno** [comment]
li ho fatti :( che cosa ho combinato

**Comment by FabioZTessitore** [comment]
Allora non li hai fatti bene. Prova con vari numeri

Il 2 feb 2017 6:53 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
si ho scoperto che il numero maggiore tra : 1 ; -2; 0 ; 0 ; -2 
il numero maggiore è 0 :(

**Comment by christian99salerno** [comment]
Prof vedete adesso spero che sia finita perchè ho fatto credo tutti i casi

**Comment by christian99salerno** [comment]
ho provato con tutti i numeri

**Comment by FabioZTessitore** [comment]
Fuochino

**Comment by christian99salerno** [comment]
:( mi state torturando dite la verità

**Comment by christian99salerno** [comment]
prof mi dite la sequenza di numeri in ordine da inserire così capisco perchè ho sbagliato perchè non riesco a trovare l'errore e sto provando tantissimi casi
